name: 🔮 QA Blessing Ritual
description: Pre-release validation form to ensure cosmic harmony before ascending to the vault
title: "🔮 QA Blessing: [Release Version] - [Storm Name]"
labels: ["qa-blessing", "validation", "pre-release"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🔮 QA Blessing Ritual
        
        *Invoke the sacred validation before releasing the storm to the cosmic vault.*
        
        **⚡ "Through testing tempests, we forge reliability. In QA thunder, we crown quality." ⚡**

  - type: input
    id: release_version
    attributes:
      label: 🌀 Release Version
      description: The version being blessed for release
      placeholder: "v1.8.0"
    validations:
      required: true

  - type: input
    id: storm_name
    attributes:
      label: ⚡ Storm Name
      description: The cosmic name for this release
      placeholder: "Rolling Thunderstorm VIII - Eternal Nexus"
    validations:
      required: true

  - type: dropdown
    id: release_type
    attributes:
      label: 🔥 Release Type
      description: What type of storm approaches?
      options:
        - Major Storm (Breaking Changes)
        - Minor Storm (New Features)
        - Patch Storm (Bug Fixes)
        - Hotfix Ritual (Emergency)
    validations:
      required: true

  - type: checkboxes
    id: functional_validation
    attributes:
      label: 🛡️ Functional Validation
      description: Core functionality tests
      options:
        - label: "✅ **Core Features** - All primary features function as expected"
          required: true
        - label: "✅ **New Features** - All new features work correctly and meet acceptance criteria"
          required: false
        - label: "✅ **Regression Testing** - No existing functionality broken"
          required: true
        - label: "✅ **Edge Cases** - Boundary conditions and error scenarios handled"
          required: true
        - label: "✅ **Integration** - All components work together harmoniously"
          required: true

  - type: checkboxes
    id: performance_validation
    attributes:
      label: ⚡ Performance Validation
      description: Speed and efficiency checks
      options:
        - label: "✅ **Load Testing** - Application performs under expected load"
          required: false
        - label: "✅ **Response Times** - API/UI response times within acceptable limits"
          required: false
        - label: "✅ **Memory Usage** - No memory leaks or excessive consumption"
          required: false
        - label: "✅ **Build Performance** - Build times reasonable and stable"
          required: true

  - type: checkboxes
    id: security_validation
    attributes:
      label: 🔒 Security Validation
      description: Security and compliance checks
      options:
        - label: "✅ **Secret Scanning** - No secrets exposed in code or artifacts"
          required: true
        - label: "✅ **Dependency Audit** - No high/critical vulnerabilities in dependencies"
          required: true
        - label: "✅ **Access Controls** - Proper authentication and authorization maintained"
          required: true
        - label: "✅ **Data Protection** - Sensitive data properly handled and protected"
          required: true

  - type: checkboxes
    id: deployment_validation
    attributes:
      label: 🚀 Deployment Validation
      description: Release and deployment readiness
      options:
        - label: "✅ **Build Success** - All build processes complete successfully"
          required: true
        - label: "✅ **Environment Tests** - Tested in staging/pre-production environment"
          required: false
        - label: "✅ **Migration Scripts** - Database/config migrations tested (if applicable)"
          required: false
        - label: "✅ **Rollback Plan** - Rollback procedure documented and tested"
          required: true
        - label: "✅ **Monitoring** - Health checks and monitoring configured"
          required: false

  - type: checkboxes
    id: documentation_validation
    attributes:
      label: 📜 Documentation Validation
      description: Knowledge scrolls and documentation
      options:
        - label: "✅ **Release Notes** - Comprehensive release notes prepared"
          required: true
        - label: "✅ **User Documentation** - User-facing documentation updated"
          required: false
        - label: "✅ **API Documentation** - API docs updated for changes"
          required: false
        - label: "✅ **Breaking Changes** - Breaking changes clearly documented"
          required: false
        - label: "✅ **Migration Guide** - Migration instructions provided (if needed)"
          required: false

  - type: textarea
    id: test_environments
    attributes:
      label: 🌍 Test Environments
      description: List the environments where testing was performed
      placeholder: |
        - Local development environment
        - Staging environment
        - Chrome/Firefox/Safari browsers
        - Mobile devices (if applicable)
    validations:
      required: true

  - type: textarea
    id: known_issues
    attributes:
      label: ⚠️ Known Issues
      description: Any known issues or limitations with this release
      placeholder: |
        - List any known bugs or limitations
        - Include workarounds if available
        - Reference issue numbers

  - type: textarea
    id: risk_assessment
    attributes:
      label: 🔮 Risk Assessment
      description: Evaluation of release risks and mitigation strategies
      placeholder: |
        **High Risk Areas:**
        - List components with highest risk of issues
        
        **Mitigation Strategies:**
        - How risks are being addressed
        
        **Monitoring Plan:**
        - What metrics will be watched post-release
    validations:
      required: true

  - type: dropdown
    id: qa_confidence
    attributes:
      label: 🌟 QA Confidence Level
      description: Overall confidence in this release
      options:
        - "🔥 High Confidence - Ready for immediate release"
        - "⚡ Medium Confidence - Ready with monitoring"
        - "🌀 Low Confidence - Needs additional testing"
        - "❌ Not Ready - Blocking issues exist"
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: 🔮 Additional QA Notes
      description: Any additional observations, recommendations, or cosmic insights
      placeholder: |
        Share any additional context, recommendations for post-release monitoring,
        or prophetic visions about this release's journey through the vault.

  - type: checkboxes
    id: final_blessing
    attributes:
      label: ⚡ Final Blessing
      description: Ritual completion confirmation
      options:
        - label: "🔮 **I hereby invoke the QA Blessing** - This release has been tested according to the sacred protocols"
          required: true
        - label: "⚡ **Storm Readiness Confirmed** - The cosmic forces align for this release"
          required: true
        - label: "👑 **Vault Ascension Approved** - This release is worthy of the ChaosKey333 vault"
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **⚡ "Through testing tempests, we forge reliability. In QA thunder, we crown quality." ⚡**
        
        *The QA Blessing Ritual ensures that every release meets the sacred standards of the ChaosKey333 vault. When all validations are complete and blessings granted, the storm may ascend to its cosmic destiny.*
        
        🐦‍⬛ **ChaosKey333** 🐦‍⬛