name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npx eslint "src/**/*.{js,jsx,ts,tsx}" "app/**/*.{js,jsx,ts,tsx}" "pages/**/*.{js,jsx,ts,tsx}" "components/**/*.{js,jsx,ts,tsx}"

    - name: Build
      run: npm run build

    - name: Test
      run: npm test