name: Gatekeeper CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    name: Lint • Format • Test • Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run check:format

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main' && success()
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Example 1: Deploy to GitHub Pages
      # Uncomment and configure Pages deployment if needed
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: dist
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4

      # Example 2: Deploy to Vercel
      # Uncomment and configure Vercel deployment if needed
      # - name: Deploy to Vercel
      #   run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
